### ISSUE TITLE
 No module named 'utils.compute_overlap'

### ISSUE THREAD

**Issue by KaggleAlbertaAI** [xuannianz/EfficientDet#61] opened 2020-01-10 04:06 UTC
Hi,
When I try to run the train.py, I got error saying no module named 'utils.compute_overlap'.
It's weird that there is a 'compute_overlap.pyx' file in 'utils' forlder.
Should we just rename the suffix as 'py' and use this file?

**Comment by KaggleAlbertaAI** [comment] 2020-01-10 04:22
ok, I figure it out by installing Cython packages.

**Comment by shivareddy37** [comment] 2020-01-14 21:02
what did you exactly install can you share I can't seem to get it to work

**Comment by KaggleAlbertaAI** [comment] 2020-01-15 09:03
> what did you exactly install can you share I can't seem to get it to work

I installed 'pyximport' package add this two lines in the code:

import pyximport
pyximport.install()

**Comment by avantgardnerio** [comment] 2020-01-16 01:17
to help others, can that get added to the requirements.txt?

**Comment by KaggleAlbertaAI** [comment] 2020-01-16 02:39
> to help others, can that get added to the requirements.txt?

I hope so, but I am not the contributor of this project. : )

**Comment by avantgardnerio** [comment] 2020-01-16 16:40
@KaggleAlbertaAI thanks for your response! When I add it there I get: ```/home/bgardner/.pyxbld/temp.linux-x86_64-3.7/pyrex/utils/compute_overlap.c:598:10: fatal error: numpy/arrayobject.h: No such file or directory
  598 | #include "numpy/arrayobject.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/usr/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1```
I assume I need to `apt install` some dev package?

**Comment by avantgardnerio** [comment] 2020-01-16 16:54
After reviewing how cython works, it seems like there was a `setup.py` that created `compute_overlap.cpython-36m-x86_64-linux-gnu.so` which is checked into git. I'm using Python 3.7, and when I compile a cython hello world, it generates a similarly named `.so` with 37 instead. @KaggleAlbertaAI are you using Python 3.6? I think this is my problem. Either the `setup.py` needs to be checked in, or all users of this project should run Python 3.6.

**Comment by avantgardnerio** [comment] 2020-01-16 20:07
Confirmed a downgrade to python 3.6 with pyenv "fixed" it. Perhaps someone more knowledgeable about Python could recreate the missing `setup.py` and send a PR. Cheers.

**Comment by shivareddy37** [comment] 2020-01-17 19:34
I found a simple solution 
created a setup.py file with
"""
from distutils.core import setup
from Cython.Build import cythonize
setup(ext_modules=cythonize("utils/compute_overlap.pyx"))
"""
python setup.py build_ext --inplace
works for me. I'm using python 3.7

**Closed** 2020-01-27 20:24 UTC
Labels: wontfix

**Comment by huizhang2017** [comment] 2020-06-01 07:45
> I found a simple solution
> created a setup.py file with
> """
> from distutils.core import setup
> from Cython.Build import cythonize
> setup(ext_modules=cythonize("utils/compute_overlap.pyx"))
> """
> python setup.py build_ext --inplace
> works for me. I'm using python 3.7

This answer (or similar answer) works for me. I think the code has been changed as follows:

from distutils.core import setup
from Cython.Build import cythonize
import numpy

setup(
    ext_modules=cythonize("utils/compute_overlap.pyx"),
    include_dirs=[numpy.get_include()]
)

You should run the following command in the Terminal first: 
python setup.py build_ext --inplace

**Comment by addisonklinke** [comment] 2021-11-15 18:00
As of today, the `setup.py` described above is included in the repository so all that's needed is to run the build command
